### ISSUE TITLE
CoseSign1Builder.create_signature closure should allow errors to propagate.

### ISSUE THREAD

**Issue by scouten-adobe** [google/coset#18]
See https://docs.rs/coset/0.1.1/coset/struct.CoseSign1Builder.html#method.create_signature.

This API is defined as:

```rust
pub fn create_signature<F>(self, aad: &[u8], signer: F) -> Self
where
    F: FnOnce(&[u8]) -> Vec<u8>
```

Some signature providers (for instance, [`openssl::sign::Signer.sign_oneshot`](https://docs.rs/openssl/0.10.35/openssl/sign/struct.Signer.html#method.sign_oneshot)), return a `Result`, but there is no way to propagate an `Error` response through this API.

Please consider redesigning this API (or providing an alternative) which would allow safe propagation of errors.

**Comment by daviddrysdale** [comment]
Yeah, makes sense (I vacillated about this when I wrote the builders in the first place).  

Would https://github.com/google/coset/pull/20/commits/350d6543f8a782f4cfa4b43dddf2c4212dacbb71 cover what you want?
