### ISSUE TITLE
Set custom claim to ClaimSet

### ISSUE THREAD

**Issue by janosimas** [google/coset#63]
I was able to set a custom claim using `ClaimsSetBuilder::text_claim` but I don't see a way of setting an integer value for the the `ClaimName`.

I was able to add it directly to `ClaimsSet::rest`, is this the expected way of doing it?

**Comment by daviddrysdale** [comment]
If the integer value you want to use is one of the IANA-defined ones in [`iana::CwtClaimName`](https://docs.rs/coset/latest/coset/iana/enum.CwtClaimName.html), you should be able to use an instance of that with the [`ClaimsSetBuilder::claim()`](https://docs.rs/coset/latest/coset/cwt/struct.ClaimsSetBuilder.html#method.claim) method ([example](https://github.com/google/coset/blob/main/src/cwt/tests.rs#L57-L67)).

However, values between 1 and 7 (inclusive) should be set with the relevant explicit builder methods (e.g. [`.cwt_id()`](https://docs.rs/coset/latest/coset/cwt/struct.ClaimsSetBuilder.html#method.cwt_id)).

**Comment by janosimas** [comment]
In my case, I want to use a non-IANA-defined. So I'm using `ClaimName::PrivateUse`.

**Comment by daviddrysdale** [comment]
In that case directly pushing to `rest` seems like the only approach at the moment.  

If there's going to be a lot of use of `PrivateUse` we should probably make that more ergonomic &ndash; maybe with a `ClaimsSetBuilder::private_claim(i64, Value) -> Self` method or somesuch?

**Comment by janosimas** [comment]
`ClaimsSetBuilder::private_claim` is what I was looking for while creating the claims.

In my case, I only have a a few items but, if nothing else, it would make the interface of `ClaimsSetBuilder` more intuitive.
