### ISSUE TITLE
Wrong context identifier for AE algorithms

### ISSUE THREAD

**Issue by janosimas** [google/coset#66]
**Issue:**
Additional authenticated data is not empty.

**Context:**
I'm doing encryption without additional authenticated data.
```
    let out = CoseEncrypt0Builder::new()
         ...
        .try_create_ciphertext(&claims.to_vec()?, b"", |claims, _| encrypt(claims))?
        .build();
```
When decrypting, the associated data is not empty:
```
    let claims = CoseEncrypt0::from_slice(&out)?.decrypt(b"", |claims, aad| {
        if !aad.is_empty() {
            return Err(Error::Foo); \\ <- Error here!!!
        }

        decrypt(claims)
    })?;
``` 

---

I debugged the error and found `Encrypt0` in the content. From the [specification](https://www.rfc-editor.org/rfc/rfc9052#section-5.4-2.2), this string should only be added for encryption with additional authenticated data.

**Comment by daviddrysdale** [comment]
Yeah, the `[try_]create_ciphertext` methods are basically only for use with AEAD algorithms but not documented as such.  

So I guess we should (for all of `CoseRecipient`, `CoseEncrypt` and `CoseEncrypt0`):
 - improve the docs to make it clear that the `cipher` argument for `[try_]create_ciphertext` must be an AEAD
 - add some additional helper functions, maybe `[try_]create_ciphertext_no_aad`, for use in the AE case.

Do you want to put a PR together?

**Comment by janosimas** [comment]
I won't be able to work on this anytime soon.

Since it has low impact, I will try to prepare a PR not so soon... :sweat_smile:

**Comment by daviddrysdale** [comment]
#67 should help with the documentation, and on looking further I'm not sure that the AE encryption case really needs any methods in the library &ndash; there's nothing to assemble/arrange and the relevant `ciphertext` fields are already `pub`.

**Comment by janosimas** [comment]
I don't follow why it wouldn't need any method.

From [rfc9052#section-5.4-2.2](https://www.rfc-editor.org/rfc/rfc9052#section-5.4-2.2), the `aad` should be empty.
Currently, even without any provided data, the `aad` contains `EncryptionContext`.

**Comment by janosimas** [comment]
Another way of doing this is to have intermediate builder types.

Something in the direction of add two new methods to `CoseEncrypt0Builder`:
- `CoseEncrypt0Builder::with_aad(&[u8])` that would return `CoseEncrypt0WithAadBuilder`
- `CoseEncrypt0Builder::without_aad()` that would return `CoseEncrypt0WithoutAadBuilder`
These new types would have `[try_]create_ciphertext`, with the options set as expected.

This approach takes advantage of the type system to forbid invalid `CoseEncrypt0` states.
The disadvantage is that it's harder to maintain and requires more design.

**Comment by daviddrysdale** [comment]
The main point of (say) `CoseEncrypt0::decrypt` is that it does conversion of `external_aad` into the actual AAD data fed to the cipher, as defined by the COSE spec.  

For an AE cipher, there's no AAD to convert or pass in, so the equivalent method would be something like:
```rust
    pub fn decrypt_no_aad<F, E>(&self, cipher: F) -> Result<Vec<u8>, E>
    where
        F: FnOnce(&[u8]) -> Result<Vec<u8>, E>,
    {
        cipher(self.ciphertext.as_ref().unwrap())
    }
```

But that means that a caller doing:
```rust
   let pt = cose_enc.decrypt_no_aad(|data| my_ae_cipher(data))?;
```
might as well just do:
```rust
   let pt = my_ae_cipher(cose_enc.ciphertext.as_ref().unwrap())?;
```

**Comment by janosimas** [comment]
The issue is not if it's possible but conformance with the standard.
This already works:
```
let claims = cose_enc.decrypt(b"", |data, aad| {
        // aad shoudl be empty but it's not
        decrypt(data)
})?;
```
In the current api, `aad` always has data. By the rfc, it should be empty.

**Comment by daviddrysdale** [comment]
`aad` always has data because the method is intended to be used with an AEAD, not an AE &ndash; as indicated by the presence of an `aad` parameter and (soon) the docs.  Don't use this method to decrypt with an AE.
