### ISSUE TITLE
CoseError doesn't seem to implement std::error::Error.

### ISSUE THREAD

**Issue by d3zd3z** [google/coset#70]
The CoseError doesn't seem to implement the standard Error trait, and it makes this error hard to manage when building other types of errors with other tools, such as thiserror, or anyhow. Even a simple impl line for this should be sufficient:
```
impl std::error::Error for CoseError{}
```
but this has to be done inside of the coset crate.

**Comment by daviddrysdale** [comment]
Try enabling the `std` feature:

https://github.com/google/coset/blob/main/src/common/mod.rs#L90-L91

**Comment by daviddrysdale** [comment]
(Reopening as a reminder to update the README to mention the `std` feature)

**Comment by d3zd3z** [comment]
Another option would be to make std the default, and could be explicitly disabled when needed. This seems to be how most crates handle this.

**Comment by daviddrysdale** [comment]
Making `std` the default would be a breaking change and necessitate a major version bump, so non-default was better.   Hopefully `core::error::Error` will stabilise and we can drop the need for the feature in future.

README updated, so closing.
