### ISSUE TITLE
Support decoding COSE_Sign1_Tagged messages

### ISSUE THREAD

**Issue by henrylyons** [google/coset#77]
When I used this crate to decode a COSE_Sign1_Tagged message, I got the following error: "got tag, expected array". 

Attached is a COSE_Sign1_Tagged message which can be used to repro this issue. The first byte of this message is D2 (tag value 18) - this value (18) is registered with IANA as Cose_Sign1 (https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml). 

Please add support for decoding COSE_Sign1_Tagged messages, to make this crate more interoperable with other COSE implementations.

[repro.zip](https://github.com/google/coset/files/11519665/repro.zip)

**Comment by daviddrysdale** [comment]
Are you using [`CoseSign1::from_tagged_slice`](https://docs.rs/coset/latest/coset/struct.CoseSign1.html#impl-TaggedCborSerializable-for-CoseSign1)?

**Comment by henrylyons** [comment]
This works, thanks for the quick triage.
