### ISSUE TITLE
Plans to Implement Signing and Verification Operations

### ISSUE THREAD

**Issue by henrylyons** [google/coset#78]
Currently, coset users have to provide closures to perform signing and verification operations. Do you have any plans to implement these operations in coset itself, or a separate crate? This functionality would be valuable for the Rust community and COSE users.

**Comment by daviddrysdale** [comment]
It was a deliberate design decision to keep cryptographic operations out of this crate, and just to focus on the COSE data structures, and there are no plans to change that.

The existing entrypoints should hopefully make it straightforward to just plug in whatever crypto crate the user wants (e.g. in [Android](https://cs.android.com/search?q=(try_create_signature%20OR%20try_create_tag%20OR%20try_create_ciphertext)%20file:%5C.rs%20-external%2Frust%2Fcrates%2Fcoset&sq=) that's BoringSSL, elsewhere might use [Tink-Rust](https://github.com/project-oak/tink-rust), or *ring*, or &hellip;).  

Happy to consider suggestions that might make that easier / more ergonomic though (cf. #18 in the past).
