### ISSUE TITLE
Feature request - one-shot support for signing and verifying detached content

### ISSUE THREAD

**Issue by henrylyons** [google/coset#79]
CoseSign1Builder.create_signature() and CoseSign1.verify_signature() construct the Sig_structure for signing/verification using the payload from the CoseSign1 message. However, these methods are more difficult to use when the content payload is detached (payload is null).

For example, the recipient of a CoseSign1 message with detached content would have to first decode the CBOR data into a CoseSign1 message and then create a copy of that message with the payload bytes, before calling verify_signature, in order to get the expected result.

The ask is to update this library to support one-shot signing and verification of CoseSign1 messages with detached content, e.g., verify_detached_signature(aad, payload, ...). Other COSE message types may benefit from this functionality as well.

For reference, here is the COSE RFC statement about detached content (https://datatracker.ietf.org/doc/html/rfc8152#page-8): "The content may be detached, but the location is still used. The content is wrapped in a bstr when present and is a nil value when detached."

**Comment by daviddrysdale** [comment]
Adding a couple of helper methods for supporting detached content sounds reasonable &ndash; do you want to send a PR?

**Comment by henrylyons** [comment]
Thank you - I have code that is ready to review, but I lack the necessary permissions to create a remote branch in this project. Can you grant me access, or create a remote branch that I can push my changes to?

**Comment by daviddrysdale** [comment]
You need to [fork the repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models#fork-and-pull-model) and create a local branch in the fork.

**Comment by daviddrysdale** [comment]
Fixed in #80
